#!/bin/bash

javadoc -d javadoc \
	-private \
	-link https://docs.oracle.com/en/java/javase/11/docs/api/ \
	-cp lib/quickcheck-0.6.jar:lib/junit-4.11.jar \
	info/kgeorgiy/ja/dubrovin/implementor/Implementor.java \
	../../java-advanced-2021/modules/info.kgeorgiy.java.advanced.implementor/info/kgeorgiy/java/advanced/implementor/Impler.java \
	../../java-advanced-2021/modules/info.kgeorgiy.java.advanced.implementor/info/kgeorgiy/java/advanced/implementor/JarImpler.java \
	../../java-advanced-2021/modules/info.kgeorgiy.java.advanced.implementor/info/kgeorgiy/java/advanced/implementor/ImplerException.java
