#!/bin/bash
echo $$ > pids
res=1
op="+"
sigterm()
{
	echo "The end"
	exit
}
usr1()
{
	op="+"
}
usr2()
{
	op="*"
}
trap 'sigterm' SIGTERM
trap 'usr1' USR1
trap 'usr2' USR2
while true;
do
	num=$(cat k)
	echo "NUM IS" $num
	case $op in
	"+")
		let res=$res+num
		;;
	"*")
		let res=$res\*num
		;;
	esac
	echo $res
	sleep 1
done
