#!/bin/bash
nice -n 8 ./while &
nice -n 0 ./while &
nice -n 1 ./while &
touch tmp
top -u anton -b -n 1 | grep while > tmp
pid1=$(awk '$4==8 {print $1}' tmp)
pid3=$(awk '$4==1 {print $1}' tmp)
rm tmp
#cpulimit -p $pid1 -l 10 -b
sudo kill -USR1 $pid3 &
