#!/bin/bash

echo "" > report.log
array=()
count=0
while true
do
	array+=(1 2 3 4 5 6 7 8 9 10)
	let count=$count+1
	if [[ $count -eq 100000 ]]
	then
		count=0
		echo ${#array[*]} >> report.log
	fi
done
